#!/bin/sh

set -e

# echo "PostInstall запущен с параметром: $1"

case "$1" in
    configure)
        #
        echo "Настройка приложения"
        a2enmod rewrite || true
        setfacl -R -m d:u:www-data:rwX /opt/arm-medo-dsp 2>/dev/null || true
        setfacl -R -m u:www-data:rwX /opt/arm-medo-dsp 2>/dev/null || true
        sed -ri "s/upload_max_filesize\s*=\s*[0-9]+M/upload_max_filesize=999M/" /etc/php/7.3/apache2/php.ini || true
        sed -ri "s/memory_limit\s*=\s*[0-9]+M/memory_limit=1G/" /etc/php/7.3/apache2/php.ini || true
        sed -ri "s/post_max_size\s*=\s*[0-9]+M/post_max_size=1G/" /etc/php/7.3/apache2/php.ini || true

        if [ -d /opt/arm-medo-dsp/backups/config ]
        then
            cp -RT /opt/arm-medo-dsp/backups/config /opt/arm-medo-dsp/api/config || true
        fi

        /usr/bin/php /opt/arm-medo-dsp/api/scripts/configure_after_install_deb.php || true

        pg_version=$(psql -V) || true
        if [[ "$pg_version" != *"psql (PostgreSQL) 11"* ]]; then
            echo "Неправильная версия PostgreSQL. Переключение на PostgreSQL 11."
            sudo pg_dropcluster --stop 14 main || true
            sudo pg_createcluster --start 11 main || true
        fi

        php_version=$(php -v) || true
        if [[ "$php_version" != *"PHP 7.3"* ]]; then
            echo "Неправильная версия PHP. Переключение на PHP 7.3."
            sudo a2dismod php8.1 || true
            sudo a2enmod php7.3 || true
            sudo update-alternatives --set php /usr/bin/php7.3 || true
            sudo cp /etc/php/8.1/mods-available/imagick.ini /etc/php/7.3/mods-available/
            sudo ln -sf /etc/php/7.3/mods-available/imagick.ini /etc/php/7.3/apache2/conf.d/20-imagick.ini
            sudo ln -sf /etc/php/7.3/mods-available/imagick.ini /etc/php/7.3/cli/conf.d/20-imagick.ini
            mv /opt/arm-medo-dsp/api/scripts/imagick.so /usr/lib/php/20180731/
            sudo service apache2 restart || true
            /usr/bin/php /opt/arm-medo-dsp/api/scripts/configure_after_install_deb.php || true
        fi

        ;;

    abort-upgrade)
        #
        echo "Postinstall ${RED}Во время обновления приложения возникли трудности!${RESET}"
        exit 1
        ;;

    *)
        echo "postinst вызван с неизвестным аргументом \`$1'" >&2
        exit 0
        ;;
esac

exit 0
